version: '3'
services:
  web:
    build: .
    environment:
      REDIS_HOST: redis
    ports:
     - "127.0.0.1:1234:1234"
    restart: unless-stopped
  redis:
    image: redis
    ports:
     - "127.0.0.1:6379:6379"
    restart: unless-stopped
